import LehmerTotient.Imports

/-!
# The completions of the eight-prime search (Section 7.4)

The search finds 21 completions `s < p < q` in integers, that is, prefixes `p₁, …, p₅` and integers `s < p < q`
with `A' p q + 1 = 2 B' (p - 1)(q - 1)`, where `A' = p₁ ⋯ p₅ s` and `B' = (p₁ - 1) ⋯ (p₅ - 1)(s - 1)`. Each is
listed with a divisor `d` of `p` or of `q`, `1 < d`, smaller than that entry, so that `p` and `q` are not both
prime. The kernel checks all of this (`decide +kernel`). Generated by `scripts/gen_eight.py`.
-/

namespace LehmerTotient

/-- A completion: the prefix, `s = p₆`, the last two entries `p < q`, and a divisor `d` of `p` or `q`. -/
structure Completion where
  pre : List ℕ
  s : ℕ
  p : ℕ
  q : ℕ
  d : ℕ

/-- `A' = p₁ ⋯ p₅ s`. -/
def Completion.A (e : Completion) : ℕ := e.pre.prod * e.s

/-- `B' = (p₁ - 1) ⋯ (p₅ - 1)(s - 1)`. -/
def Completion.B (e : Completion) : ℕ := (e.pre.map (· - 1)).prod * (e.s - 1)

/-- The check: the equation, `s < p < q`, and `d` a proper divisor of `p` or of `q`. -/
def Completion.check (e : Completion) : Bool :=
  (e.A * e.p * e.q + 1 == 2 * e.B * (e.p - 1) * (e.q - 1)) && decide (e.s < e.p) && decide (e.p < e.q) &&
    decide (1 < e.d) && ((decide (e.d < e.p) && e.p % e.d == 0) || (decide (e.d < e.q) && e.q % e.d == 0))

/-- The 21 completions found by the search, in increasing order. -/
def eightCompletions : List Completion := [
  ⟨[3, 5, 17, 257, 65537], 4294967459, 113407896044937359, 53998014529576766405, 5⟩,
  ⟨[3, 5, 17, 257, 65537], 4294967969, 27419312914203719, 78410484361621539095, 5⟩,
  ⟨[3, 5, 17, 257, 65537], 4596195557, 65533391633, 355694953689628478107898909, 17⟩,
  ⟨[3, 5, 17, 353, 929], 83623937, 6992962672132097, 48901526933832864378258473353217, 73⟩,
  ⟨[3, 5, 17, 353, 929], 83623937, 6992962672132109, 3761655917987149868754656841413, 23⟩,
  ⟨[3, 5, 17, 353, 929], 83623937, 6992962672132133, 1321662890103597733105801894829, 7⟩,
  ⟨[3, 5, 17, 353, 929], 83623937, 6992962672132205, 448637861778290088240615262565, 5⟩,
  ⟨[3, 5, 17, 353, 929], 83623937, 6992962672132577, 101666376161821665281374421537, 7⟩,
  ⟨[3, 5, 17, 353, 929], 83623937, 6992962672133513, 34510604752182615676360065209, 163⟩,
  ⟨[3, 5, 17, 353, 929], 83623937, 6992962672136129, 12125347615636265808021946433, 13⟩,
  ⟨[3, 5, 17, 353, 929], 83623937, 6992962672184525, 932719047363090873852887045, 5⟩,
  ⟨[3, 5, 17, 353, 929], 83623937, 6992993474312885, 1587606496673670800285, 5⟩,
  ⟨[3, 5, 17, 353, 929], 83623937, 6993363100482353, 122130031709672029649, 7⟩,
  ⟨[3, 5, 17, 353, 929], 83623937, 6994102352821289, 42915087657563987993, 31⟩,
  ⟨[3, 5, 17, 353, 929], 83623937, 6996320109838097, 14572126024240927217, 2341⟩,
  ⟨[3, 5, 17, 353, 929], 83623937, 7007778521091605, 3307615631509967165, 5⟩,
  ⟨[3, 5, 17, 353, 929], 83623937, 7036609362310109, 1127387813562039413, 1471⟩,
  ⟨[3, 5, 17, 353, 929], 83623937, 7117187867254133, 400645207579396829, 7⟩,
  ⟨[3, 5, 17, 353, 929], 83623937, 8607890208718577, 37273904588075537, 7⟩,
  ⟨[3, 5, 17, 353, 929], 83625827, 3698107203375, 122571840777322899429285, 3⟩,
  ⟨[3, 5, 17, 353, 929], 83760029, 51467329335, 11874809561886335859, 3⟩]

theorem eightCompletions_length : eightCompletions.length = 21 := by decide +kernel

theorem eightCompletions_check : eightCompletions.all Completion.check = true := by decide +kernel

/-- Each of the 21 completions satisfies `A' p q + 1 = 2 B' (p - 1)(q - 1)` with `s < p < q`, and `p` and `q`
are not both prime. -/
theorem eight_completions {e : Completion} (he : e ∈ eightCompletions) :
    e.A * e.p * e.q + 1 = 2 * e.B * (e.p - 1) * (e.q - 1) ∧ e.s < e.p ∧ e.p < e.q ∧
      ¬ (e.p.Prime ∧ e.q.Prime) := by
  have h := List.all_eq_true.mp eightCompletions_check e he
  simp only [Completion.check, Bool.and_eq_true, Bool.or_eq_true, beq_iff_eq, decide_eq_true_eq] at h
  obtain ⟨⟨⟨⟨heq, hsp⟩, hpq⟩, hd⟩, hdiv⟩ := h
  refine ⟨heq, hsp, hpq, ?_⟩
  rintro ⟨hp, hq⟩
  rcases hdiv with ⟨hdp, hmod⟩ | ⟨hdq, hmod⟩
  · exact Nat.not_prime_of_dvd_of_lt (Nat.dvd_of_mod_eq_zero hmod) hd hdp hp
  · exact Nat.not_prime_of_dvd_of_lt (Nat.dvd_of_mod_eq_zero hmod) hd hdq hq

end LehmerTotient
