import LehmerTotient.ExtBasic

/-!
# The Fermat-type solutions (Theorem 1.6 (iii))

`fermatList` holds the eight Fermat-type solutions in (1.3), `1, 3, 15, 255, 65535, 83623935,
4294967295, 6992962672132095`.  `Reached` is the closure of `1` under one- and two-prime
extensions, and `reached_iff` shows that it consists of exactly these eight numbers.  The
primality certificates and the case analysis below are generated by `scripts/gen_ext.py`.
-/

namespace LehmerTotient

open Nat

/-! ### Primality certificates -/

theorem prime_22253377 : (22253377 : ℕ).Prime :=
  lucas_cert _ 5 [(2, 6), (3, 1), (115903, 1)] (by norm_num) (by norm_num)
    (by intro x hx; simp at hx; rcases hx with rfl | rfl | rfl <;> norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem prime_579535339 : (579535339 : ℕ).Prime :=
  lucas_cert _ 34 [(2, 1), (3, 1), (17, 1), (43, 1), (229, 1), (577, 1)] (by norm_num) (by norm_num)
    (by intro x hx; simp at hx; rcases hx with rfl | rfl | rfl | rfl | rfl | rfl <;> norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem prime_18446744069414584321 : (18446744069414584321 : ℕ).Prime :=
  lucas_cert _ 7 [(2, 32), (3, 1), (5, 1), (17, 1), (257, 1), (65537, 1)] (by norm_num) (by norm_num)
    (by intro x hx; simp at hx; rcases hx with rfl | rfl | rfl | rfl | rfl | rfl <;> norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem prime_30802180789 : (30802180789 : ℕ).Prime :=
  lucas_cert _ 2 [(2, 2), (3, 2), (331, 1), (2584943, 1)] (by norm_num) (by norm_num)
    (by intro x hx; simp at hx; rcases hx with rfl | rfl | rfl | rfl <;> norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem prime_953230871 : (953230871 : ℕ).Prime :=
  lucas_cert _ 13 [(2, 1), (5, 1), (29, 1), (3287003, 1)] (by norm_num) (by norm_num)
    (by intro x hx; simp at hx; rcases hx with rfl | rfl | rfl | rfl <;> norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem prime_30280941915943441 : (30280941915943441 : ℕ).Prime :=
  lucas_cert _ 11 [(2, 4), (3, 1), (5, 1), (132361, 1), (953230871, 1)] (by norm_num) (by norm_num)
    (by intro x hx; simp at hx; rcases hx with rfl | rfl | rfl | rfl | rfl <;> first | exact prime_953230871 | norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem prime_83623937 : (83623937 : ℕ).Prime :=
  lucas_cert _ 3 [(2, 18), (11, 1), (29, 1)] (by norm_num) (by norm_num)
    (by intro x hx; simp at hx; rcases hx with rfl | rfl | rfl <;> norm_num)
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

/-- The Fermat-type solutions in (1.3) other than `2`. -/
def fermatList : List ℕ := [1, 3, 15, 255, 65535, 83623935, 4294967295, 6992962672132095]

/-- The closure of `1` under the extensions of Theorem 1.6 (i) and (ii). -/
inductive Reached : ℕ → Prop
  | one : Reached 1
  | ext1 {n0 q : ℕ} : Reached n0 → q.Prime → ¬ q ∣ n0 → FermatType (n0 * q) → Reached (n0 * q)
  | ext2 {n0 p q : ℕ} : Reached n0 → p.Prime → q.Prime → p < q → ¬ p ∣ n0 → ¬ q ∣ n0 →
      FermatType (n0 * p * q) → Reached (n0 * p * q)

theorem fermatType_one : FermatType 1 := by simp [FermatType]

theorem reached_1 : Reached 1 := Reached.one

theorem fermatType_3 : FermatType 3 := by
  have h := (one_prime_ext (q := 3) fermatType_one (by norm_num) (by norm_num)).mpr rfl
  norm_num at h
  exact h

theorem reached_3 : Reached 3 := by
  have h := Reached.ext1 (q := 3) reached_1 (by norm_num) (by norm_num : ¬ (3 : ℕ) ∣ 1)
    (by norm_num; exact fermatType_3)
  norm_num at h
  exact h

theorem fermatType_15 : FermatType 15 := by
  have h := (one_prime_ext (q := 5) fermatType_3 (by norm_num) (by norm_num)).mpr rfl
  norm_num at h
  exact h

theorem reached_15 : Reached 15 := by
  have h := Reached.ext1 (q := 5) reached_3 (by norm_num) (by norm_num : ¬ (5 : ℕ) ∣ 3)
    (by norm_num; exact fermatType_15)
  norm_num at h
  exact h

theorem fermatType_255 : FermatType 255 := by
  have h := (one_prime_ext (q := 17) fermatType_15 (by norm_num) (by norm_num)).mpr rfl
  norm_num at h
  exact h

theorem reached_255 : Reached 255 := by
  have h := Reached.ext1 (q := 17) reached_15 (by norm_num) (by norm_num : ¬ (17 : ℕ) ∣ 15)
    (by norm_num; exact fermatType_255)
  norm_num at h
  exact h

theorem fermatType_65535 : FermatType 65535 := by
  have h := (one_prime_ext (q := 257) fermatType_255 (by norm_num) (by norm_num)).mpr rfl
  norm_num at h
  exact h

theorem reached_65535 : Reached 65535 := by
  have h := Reached.ext1 (q := 257) reached_255 (by norm_num) (by norm_num : ¬ (257 : ℕ) ∣ 255)
    (by norm_num; exact fermatType_65535)
  norm_num at h
  exact h

theorem fermatType_4294967295 : FermatType 4294967295 := by
  have h := (one_prime_ext (q := 65537) fermatType_65535 (by norm_num) (by norm_num)).mpr rfl
  norm_num at h
  exact h

theorem reached_4294967295 : Reached 4294967295 := by
  have h := Reached.ext1 (q := 65537) reached_65535 (by norm_num) (by norm_num : ¬ (65537 : ℕ) ∣ 65535)
    (by norm_num; exact fermatType_4294967295)
  norm_num at h
  exact h

theorem fermatType_83623935 : FermatType 83623935 := by
  have h := two_prime_ext_of_factor fermatType_255 (d := 97) (e := 673) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num)
  norm_num at h
  exact h

theorem reached_83623935 : Reached 83623935 := by
  have h := Reached.ext2 (p := 353) (q := 929) reached_255 (by norm_num : (353 : ℕ).Prime)
    (by norm_num : (929 : ℕ).Prime) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num; exact fermatType_83623935)
  norm_num at h
  exact h

theorem fermatType_6992962672132095 : FermatType 6992962672132095 := by
  have h := (one_prime_ext (q := 83623937) fermatType_83623935 prime_83623937 (by norm_num)).mpr rfl
  norm_num at h
  exact h

theorem reached_6992962672132095 : Reached 6992962672132095 := by
  have h := Reached.ext1 (q := 83623937) reached_83623935 prime_83623937 (by norm_num : ¬ (83623937 : ℕ) ∣ 83623935)
    (by norm_num; exact fermatType_6992962672132095)
  norm_num at h
  exact h

theorem fermatList_fermatType : ∀ n ∈ fermatList, FermatType n := by
  intro n hn
  simp only [fermatList, List.mem_cons, List.not_mem_nil, or_false] at hn
  rcases hn with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · exact fermatType_one
  · exact fermatType_3
  · exact fermatType_15
  · exact fermatType_255
  · exact fermatType_65535
  · exact fermatType_83623935
  · exact fermatType_4294967295
  · exact fermatType_6992962672132095

theorem fermatList_reached : ∀ n ∈ fermatList, Reached n := by
  intro n hn
  simp only [fermatList, List.mem_cons, List.not_mem_nil, or_false] at hn
  rcases hn with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · exact reached_1
  · exact reached_3
  · exact reached_15
  · exact reached_255
  · exact reached_65535
  · exact reached_83623935
  · exact reached_4294967295
  · exact reached_6992962672132095

/-- No one-prime extension leaves the list. -/
theorem closed_one : ∀ n0 ∈ fermatList, ∀ q, q.Prime → ¬ q ∣ n0 → FermatType (n0 * q) →
    n0 * q ∈ fermatList := by
  intro n0 hn0 q hq hqn h
  have hq2 := (one_prime_ext (fermatList_fermatType n0 hn0) hq hqn).mp h
  subst hq2
  simp only [fermatList, List.mem_cons, List.not_mem_nil, or_false] at hn0
  rcases hn0 with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl

  · decide

  · decide

  · decide

  · decide

  · decide

  · decide

  · exact absurd hq (by norm_num)

  · exact absurd hq (by norm_num)

lemma closed_two_1 : ∀ d ∈ ([1, 3] : List ℕ), ∀ e, d * e = 3 → d < e →
    (1 + 1 + d).Prime → (1 + 1 + e).Prime →
    1 * (1 + 1 + d) * (1 + 1 + e) ∈ fermatList := by
  intro d hd e he hlt hp hq
  simp at hd
  rcases hd with rfl | rfl
  · obtain rfl : e = 3 := by omega
    decide
  · omega

lemma closed_two_3 : ∀ d ∈ ([1, 13] : List ℕ), ∀ e, d * e = 13 → d < e →
    (3 + 1 + d).Prime → (3 + 1 + e).Prime →
    3 * (3 + 1 + d) * (3 + 1 + e) ∈ fermatList := by
  intro d hd e he hlt hp hq
  simp at hd
  rcases hd with rfl | rfl
  · obtain rfl : e = 13 := by omega
    decide
  · omega

lemma closed_two_15 : ∀ d ∈ ([1, 241] : List ℕ), ∀ e, d * e = 241 → d < e →
    (15 + 1 + d).Prime → (15 + 1 + e).Prime →
    15 * (15 + 1 + d) * (15 + 1 + e) ∈ fermatList := by
  intro d hd e he hlt hp hq
  simp at hd
  rcases hd with rfl | rfl
  · obtain rfl : e = 241 := by omega
    decide
  · omega

lemma closed_two_255 : ∀ d ∈ ([1, 673, 97, 65281] : List ℕ), ∀ e, d * e = 65281 → d < e →
    (255 + 1 + d).Prime → (255 + 1 + e).Prime →
    255 * (255 + 1 + d) * (255 + 1 + e) ∈ fermatList := by
  intro d hd e he hlt hp hq
  simp at hd
  rcases hd with rfl | rfl | rfl | rfl
  · obtain rfl : e = 65281 := by omega
    decide
  · omega
  · obtain rfl : e = 673 := by omega
    decide
  · omega

lemma closed_two_65535 : ∀ d ∈ ([1, 22253377, 193, 4294901761] : List ℕ), ∀ e, d * e = 4294901761 → d < e →
    (65535 + 1 + d).Prime → (65535 + 1 + e).Prime →
    65535 * (65535 + 1 + d) * (65535 + 1 + e) ∈ fermatList := by
  intro d hd e he hlt hp hq
  simp at hd
  rcases hd with rfl | rfl | rfl | rfl
  · obtain rfl : e = 4294901761 := by omega
    exact absurd hq (by norm_num)
  · omega
  · obtain rfl : e = 22253377 := by omega
    exact absurd hq (by norm_num)
  · omega

lemma closed_two_83623935 : ∀ d ∈ ([1, 579535339, 180097, 104372575947883, 67, 38828867713, 12066499, 6992962588508161] : List ℕ), ∀ e, d * e = 6992962588508161 → d < e →
    (83623935 + 1 + d).Prime → (83623935 + 1 + e).Prime →
    83623935 * (83623935 + 1 + d) * (83623935 + 1 + e) ∈ fermatList := by
  intro d hd e he hlt hp hq
  simp at hd
  rcases hd with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · obtain rfl : e = 6992962588508161 := by omega
    exact absurd hq (by norm_num)
  · omega
  · obtain rfl : e = 38828867713 := by omega
    exact absurd hp (by norm_num)
  · omega
  · obtain rfl : e = 104372575947883 := by omega
    exact absurd hp (by norm_num)
  · omega
  · obtain rfl : e = 579535339 := by omega
    exact absurd hp (by norm_num)
  · omega

lemma closed_two_4294967295 : ∀ d ∈ ([1, 18446744069414584321] : List ℕ), ∀ e, d * e = 18446744069414584321 → d < e →
    (4294967295 + 1 + d).Prime → (4294967295 + 1 + e).Prime →
    4294967295 * (4294967295 + 1 + d) * (4294967295 + 1 + e) ∈ fermatList := by
  intro d hd e he hlt hp hq
  simp at hd
  rcases hd with rfl | rfl
  · obtain rfl : e = 18446744069414584321 := by omega
    exact absurd hp (by norm_num)
  · omega

lemma closed_two_6992962672132095 : ∀ d ∈ ([1, 30280941915943441, 30802180789, 932719047356097911180754949, 109, 3300622668837835069, 3357437706001, 101666376161814672318702289441, 37, 1120394850889907317, 1139680689193, 34510604752175622713687933113, 4033, 122123038746999897553, 124225195122037, 3761655917987142875791984709317, 13, 393652244907264733, 400428350257, 12125347615629272845349814337, 1417, 42908094694891855897, 43646690178013, 1321662890103590740143129762733, 481, 14565133061568795121, 14815848959509, 448637861778283095277943130469, 52429, 1587599503710998668189, 1614927536586481, 48901526933832857385295801221121] : List ℕ), ∀ e, d * e = 48901526933832857385295801221121 → d < e →
    (6992962672132095 + 1 + d).Prime → (6992962672132095 + 1 + e).Prime →
    6992962672132095 * (6992962672132095 + 1 + d) * (6992962672132095 + 1 + e) ∈ fermatList := by
  intro d hd e he hlt hp hq
  simp at hd
  rcases hd with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · obtain rfl : e = 48901526933832857385295801221121 := by omega
    exact absurd hp (by norm_num)
  · omega
  · obtain rfl : e = 1587599503710998668189 := by omega
    exact absurd hp (by norm_num)
  · omega
  · obtain rfl : e = 448637861778283095277943130469 := by omega
    exact absurd hp (by norm_num)
  · omega
  · obtain rfl : e = 14565133061568795121 := by omega
    exact absurd hq (by norm_num)
  · omega
  · obtain rfl : e = 1321662890103590740143129762733 := by omega
    exact absurd hq (by norm_num)
  · omega
  · obtain rfl : e = 42908094694891855897 := by omega
    exact absurd hp (by norm_num)
  · omega
  · obtain rfl : e = 12125347615629272845349814337 := by omega
    exact absurd hp (by norm_num)
  · omega
  · obtain rfl : e = 393652244907264733 := by omega
    exact absurd hq (by norm_num)
  · omega
  · obtain rfl : e = 3761655917987142875791984709317 := by omega
    exact absurd hq (by norm_num)
  · omega
  · obtain rfl : e = 122123038746999897553 := by omega
    exact absurd hp (by norm_num)
  · omega
  · obtain rfl : e = 34510604752175622713687933113 := by omega
    exact absurd hq (by norm_num)
  · omega
  · obtain rfl : e = 1120394850889907317 := by omega
    exact absurd hp (by norm_num)
  · omega
  · obtain rfl : e = 101666376161814672318702289441 := by omega
    exact absurd hp (by norm_num)
  · omega
  · obtain rfl : e = 3300622668837835069 := by omega
    exact absurd hp (by norm_num)
  · omega
  · obtain rfl : e = 932719047356097911180754949 := by omega
    exact absurd hp (by norm_num)
  · omega
  · obtain rfl : e = 30280941915943441 := by omega
    exact absurd hp (by norm_num)
  · omega

/-- No two-prime extension leaves the list. -/
theorem closed_two : ∀ n0 ∈ fermatList, ∀ p q, p.Prime → q.Prime → p < q → ¬ p ∣ n0 →
    ¬ q ∣ n0 → FermatType (n0 * p * q) → n0 * p * q ∈ fermatList := by
  intro n0 hn0 p q hp hq hpq hpn hqn h
  have h0 := fermatList_fermatType n0 hn0
  have E := (two_prime_ext h0 hp hq hpq hpn hqn).mp h
  obtain ⟨hp1, hq1⟩ := two_prime_ext_pos h0.pos hp.two_le hpq E
  obtain ⟨d, rfl⟩ : ∃ d, p = n0 + 1 + d := ⟨p - (n0 + 1), by omega⟩
  obtain ⟨e, rfl⟩ : ∃ e, q = n0 + 1 + e := ⟨q - (n0 + 1), by omega⟩
  have hde : d * e = n0 ^ 2 + n0 + 1 := by
    have : (d : ℤ) * e = n0 ^ 2 + n0 + 1 := by
      push_cast at E
      linear_combination E
    exact_mod_cast this
  have hdlt : d < e := by omega
  have hdvd : d ∣ n0 ^ 2 + n0 + 1 := ⟨e, hde.symm⟩
  simp only [fermatList, List.mem_cons, List.not_mem_nil, or_false] at hn0
  rcases hn0 with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl

  · have hd := mem_subprods_of_dvd (d := d) [3]
      (by intro x hx; simp only [List.mem_cons, List.not_mem_nil, or_false] at hx
          rcases hx with rfl
          all_goals norm_num)
      (by rw [show ([3] : List ℕ).prod = 1 ^ 2 + 1 + 1 by norm_num]; exact hdvd)
    rw [show subprods [3] = [1, 3] by decide] at hd
    exact closed_two_1 d hd e (by norm_num [hde]) hdlt hp hq

  · have hd := mem_subprods_of_dvd (d := d) [13]
      (by intro x hx; simp only [List.mem_cons, List.not_mem_nil, or_false] at hx
          rcases hx with rfl
          all_goals norm_num)
      (by rw [show ([13] : List ℕ).prod = 3 ^ 2 + 3 + 1 by norm_num]; exact hdvd)
    rw [show subprods [13] = [1, 13] by decide] at hd
    exact closed_two_3 d hd e (by norm_num [hde]) hdlt hp hq

  · have hd := mem_subprods_of_dvd (d := d) [241]
      (by intro x hx; simp only [List.mem_cons, List.not_mem_nil, or_false] at hx
          rcases hx with rfl
          all_goals norm_num)
      (by rw [show ([241] : List ℕ).prod = 15 ^ 2 + 15 + 1 by norm_num]; exact hdvd)
    rw [show subprods [241] = [1, 241] by decide] at hd
    exact closed_two_15 d hd e (by norm_num [hde]) hdlt hp hq

  · have hd := mem_subprods_of_dvd (d := d) [97, 673]
      (by intro x hx; simp only [List.mem_cons, List.not_mem_nil, or_false] at hx
          rcases hx with rfl | rfl
          all_goals norm_num)
      (by rw [show ([97, 673] : List ℕ).prod = 255 ^ 2 + 255 + 1 by norm_num]; exact hdvd)
    rw [show subprods [97, 673] = [1, 673, 97, 65281] by decide] at hd
    exact closed_two_255 d hd e (by norm_num [hde]) hdlt hp hq

  · have hd := mem_subprods_of_dvd (d := d) [193, 22253377]
      (by intro x hx; simp only [List.mem_cons, List.not_mem_nil, or_false] at hx
          rcases hx with rfl | rfl
          all_goals first | exact prime_22253377 | norm_num)
      (by rw [show ([193, 22253377] : List ℕ).prod = 65535 ^ 2 + 65535 + 1 by norm_num]; exact hdvd)
    rw [show subprods [193, 22253377] = [1, 22253377, 193, 4294901761] by decide] at hd
    exact closed_two_65535 d hd e (by norm_num [hde]) hdlt hp hq

  · have hd := mem_subprods_of_dvd (d := d) [67, 180097, 579535339]
      (by intro x hx; simp only [List.mem_cons, List.not_mem_nil, or_false] at hx
          rcases hx with rfl | rfl | rfl
          all_goals first | exact prime_579535339 | norm_num)
      (by rw [show ([67, 180097, 579535339] : List ℕ).prod = 83623935 ^ 2 + 83623935 + 1 by norm_num]; exact hdvd)
    rw [show subprods [67, 180097, 579535339] = [1, 579535339, 180097, 104372575947883, 67, 38828867713, 12066499, 6992962588508161] by decide] at hd
    exact closed_two_83623935 d hd e (by norm_num [hde]) hdlt hp hq

  · have hd := mem_subprods_of_dvd (d := d) [18446744069414584321]
      (by intro x hx; simp only [List.mem_cons, List.not_mem_nil, or_false] at hx
          rcases hx with rfl
          all_goals exact prime_18446744069414584321)
      (by rw [show ([18446744069414584321] : List ℕ).prod = 4294967295 ^ 2 + 4294967295 + 1 by norm_num]; exact hdvd)
    rw [show subprods [18446744069414584321] = [1, 18446744069414584321] by decide] at hd
    exact closed_two_4294967295 d hd e (by norm_num [hde]) hdlt hp hq

  · have hd := mem_subprods_of_dvd (d := d) [13, 37, 109, 30802180789, 30280941915943441]
      (by intro x hx; simp only [List.mem_cons, List.not_mem_nil, or_false] at hx
          rcases hx with rfl | rfl | rfl | rfl | rfl
          all_goals first | exact prime_30802180789 | exact prime_30280941915943441 | norm_num)
      (by rw [show ([13, 37, 109, 30802180789, 30280941915943441] : List ℕ).prod = 6992962672132095 ^ 2 + 6992962672132095 + 1 by norm_num]; exact hdvd)
    rw [show subprods [13, 37, 109, 30802180789, 30280941915943441] = [1, 30280941915943441, 30802180789, 932719047356097911180754949, 109, 3300622668837835069, 3357437706001, 101666376161814672318702289441, 37, 1120394850889907317, 1139680689193, 34510604752175622713687933113, 4033, 122123038746999897553, 124225195122037, 3761655917987142875791984709317, 13, 393652244907264733, 400428350257, 12125347615629272845349814337, 1417, 42908094694891855897, 43646690178013, 1321662890103590740143129762733, 481, 14565133061568795121, 14815848959509, 448637861778283095277943130469, 52429, 1587599503710998668189, 1614927536586481, 48901526933832857385295801221121] by decide] at hd
    exact closed_two_6992962672132095 d hd e (by norm_num [hde]) hdlt hp hq

/-- Theorem 1.6 (iii): the closure of `1` under one- and two-prime extensions consists of
exactly the eight Fermat-type solutions in `fermatList`. -/
theorem reached_iff (n : ℕ) : Reached n ↔ n ∈ fermatList := by
  constructor
  · intro h
    induction h with
    | one => decide
    | ext1 _ hq hqn hft ih => exact closed_one _ ih _ hq hqn hft
    | ext2 _ hp hq hpq hpn hqn hft ih => exact closed_two _ ih _ _ hp hq hpq hpn hqn hft
  · exact fermatList_reached n

end LehmerTotient
