import LehmerTotient

/-! Axiom audit: every theorem below must depend only on `propext`,
`Classical.choice` and `Quot.sound`. `lake env lean Check.lean` prints the list. -/

open LehmerTotient

#print axioms odd_of_dvd
#print axioms squarefree_of_dvd
#print axioms prime_not_dvd_sub_one
#print axioms prime_not_dvd_quotient
#print axioms not_prime_of_dvd_add_one
#print axioms two_le_quotient
#print axioms quotient_mod_three
#print axioms P_lt_two
#print axioms bounds_minus
#print axioms bounds_plus
#print axioms last_two
#print axioms last_two_converse
#print axioms last_two_general
#print axioms class_of_solution
#print axioms solution_of_class
#print axioms coset_of_divisor
#print axioms box
#print axioms sum_identity
#print axioms sum_converse
#print axioms cofactor_class
#print axioms at_most_one_divisor
#print axioms isCoprime_of_prune
#print axioms firstHit_spec
#print axioms quotient_eq_two_of_not_three_dvd
#print axioms quotient_eq_two_of_card_le_seven
#print axioms card_ge_of_three_dvd
#print axioms three_dvd_consequences
#print axioms theorem_quotient
#print axioms one_prime_ext
#print axioms two_prime_ext
#print axioms two_prime_ext_of_factor
#print axioms three_prime_ext
#print axioms three_prime_identity
#print axioms pseudo_solution
#print axioms pseudo_solution_prune
#print axioms lucas_cert
#print axioms reached_iff
#print axioms gcd_of_product_eq
#print axioms three_parity
#print axioms three_parity_lehmer
#print axioms three_parity_companion
#print axioms lehmer_coprime_three_free
#print axioms local_witness
#print axioms three_obstruction
#print axioms companion_step
#print axioms lehmer_step
#print axioms companion_all
#print axioms lehmer_all
#print axioms pseudoXs_companion
#print axioms pseudoXs_three
#print axioms companion_pseudo_prime_to_three
#print axioms lehmer_pseudo_prime_to_three
#print axioms eight_reduction
#print axioms trial_dvd_iff
#print axioms sigma_identities
#print axioms sigma_class
#print axioms sigma_range
#print axioms sigma_converse
#print axioms sieve_keeps
#print axioms eight_kept
#print axioms int_kept
#print axioms no_small_factor_of_prime
#print axioms fermat_prefix
#print axioms eight_completions
#print axioms lehmer_ext_eq
#print axioms lehmer_ext_sorted
#print axioms lehmer_ext_pairwise
#print axioms prime_dvd_mod_five
#print axioms dvd_mod_five
#print axioms lehmer_ext_five
#print axioms Product.E_comp
#print axioms Product.E_mono
#print axioms Product.tail
#print axioms Product.major
#print axioms Product.cn_prod_one_sub
#print axioms Product.cook_nielsen
#print axioms Product.deficit
#print axioms Product.deficit_one
#print axioms Product.deficit_attained
#print axioms Product.size_bounds
#print axioms Product.light
#print axioms degree_one_unique
#print axioms three_entries_identity
#print axioms no_linear_factorisation
#print axioms fermat_entry
#print axioms fermat_tuple
#print axioms fermat_tuple_carmichael
#print axioms largest_coprime_defect
#print axioms largest_sub_one
#print axioms largest_coprime_entry
#print axioms largest_defect_one
#print axioms largest_three_dvd
#print axioms largest_three_not_dvd
#print axioms defect_pos_iff
#print axioms defect_step
#print axioms defect_rest_bounds
#print axioms defect_dvd_iff
#print axioms defect_completion
