import os
# Generates lean/LehmerTotient/Ext.lean: Theorem 1.6 (iii) for the eight Fermat-type solutions.
from sympy import factorint, isprime
L=[1,3,15,255,65535,83623935,4294967295,6992962672132095]
def spf(x):
    f=factorint(x, limit=10**7)
    return min(f)
def lucas(p):
    f=factorint(p-1); a=2
    while not (pow(a,p-1,p)==1 and all(pow(a,(p-1)//q,p)!=1 for q in f)): a+=1
    return a, sorted(f.items())
SMALL=10**7   # norm_num proves primality by trial division below this
certs={}      # p -> name
out=[]
def prime_proof(p):
    """Returns a term proving (p : ℕ).Prime, emitting certificates as needed."""
    if p < SMALL: return "(by norm_num)"
    if p in certs: return certs[p]
    a,fs=lucas(p)
    subs=[prime_proof(q) for q,_ in fs]
    name=f"prime_{p}"
    fl=", ".join(f"({q}, {e})" for q,e in fs)
    pats=" | ".join("rfl" for _ in fs)
    alts=[f"exact {certs[q]}" for q,_ in fs if q>=SMALL] + (["norm_num"] if any(q<SMALL for q,_ in fs) else [])
    tac=alts[0] if len(alts)==1 else "first | " + " | ".join(alts)
    out.append(f"""theorem {name} : ({p} : ℕ).Prime :=
  lucas_cert _ {a} [{fl}] (by norm_num) (by norm_num)
    (by intro x hx; simp at hx; rcases hx with {pats} <;> {tac})
    (by decide +kernel) (by decide +kernel) (by decide +kernel)
""")
    certs[p]=name
    return name
def subprods(ps):
    if not ps: return [1]
    r=subprods(ps[1:]); return r+[ps[0]*x for x in r]
header='''import LehmerTotient.ExtBasic

/-!
# The Fermat-type solutions (Theorem 1.6 (iii))

`fermatList` holds the eight Fermat-type solutions in (1.3), `1, 3, 15, 255, 65535, 83623935,
4294967295, 6992962672132095`.  `Reached` is the closure of `1` under one- and two-prime
extensions, and `reached_iff` shows that it consists of exactly these eight numbers.  The
primality certificates and the case analysis below are generated by `scripts/gen_ext.py`.
-/

namespace LehmerTotient

open Nat

/-! ### Primality certificates -/

'''
facs={}
for n0 in L:
    D=n0*n0+n0+1
    facs[n0]=sorted(factorint(D).keys())
    for p in facs[n0]: prime_proof(p)
prime_proof(83623937); prime_proof(65537)
body=[]
body.append("""/-- The Fermat-type solutions in (1.3) other than `2`. -/
def fermatList : List ℕ := [""" + ", ".join(map(str,L)) + """]

/-- The closure of `1` under the extensions of Theorem 1.6 (i) and (ii). -/
inductive Reached : ℕ → Prop
  | one : Reached 1
  | ext1 {n0 q : ℕ} : Reached n0 → q.Prime → ¬ q ∣ n0 → FermatType (n0 * q) → Reached (n0 * q)
  | ext2 {n0 p q : ℕ} : Reached n0 → p.Prime → q.Prime → p < q → ¬ p ∣ n0 → ¬ q ∣ n0 →
      FermatType (n0 * p * q) → Reached (n0 * p * q)

theorem fermatType_one : FermatType 1 := by simp [FermatType]
""")
# chain
chain=[(1,3,'one'),(3,15,'one'),(15,255,'one'),(255,65535,'one'),(65535,4294967295,'one'),
       (255,83623935,'two',97,673),(83623935,6992962672132095,'one')]
ftname=lambda n: f"fermatType_{n}"
reachname=lambda n: f"reached_{n}"
body.append("theorem reached_1 : Reached 1 := Reached.one\n")
for c in chain:
    n0,n=c[0],c[1]
    if c[2]=='one':
        q=n0+2; pq=prime_proof(q)
        body.append(f"""theorem {ftname(n)} : FermatType {n} := by
  have h := (one_prime_ext (q := {q}) {ftname(n0) if n0>1 else 'fermatType_one'} {pq} (by norm_num)).mpr rfl
  norm_num at h
  exact h

theorem {reachname(n)} : Reached {n} := by
  have h := Reached.ext1 (q := {q}) {reachname(n0)} {pq} (by norm_num : ¬ ({q} : ℕ) ∣ {n0})
    (by norm_num; exact {ftname(n)})
  norm_num at h
  exact h
""")
    else:
        d,e=c[3],c[4]; p=n0+1+d; q=n0+1+e
        body.append(f"""theorem {ftname(n)} : FermatType {n} := by
  have h := two_prime_ext_of_factor {ftname(n0)} (d := {d}) (e := {e}) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num)
  norm_num at h
  exact h

theorem {reachname(n)} : Reached {n} := by
  have h := Reached.ext2 (p := {p}) (q := {q}) {reachname(n0)} (by norm_num : ({p} : ℕ).Prime)
    (by norm_num : ({q} : ℕ).Prime) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num; exact {ftname(n)})
  norm_num at h
  exact h
""")
body.append("""theorem fermatList_fermatType : ∀ n ∈ fermatList, FermatType n := by
  intro n hn
  simp only [fermatList, List.mem_cons, List.not_mem_nil, or_false] at hn
  rcases hn with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · exact fermatType_one
""" + "".join(f"  · exact {ftname(n)}\n" for n in L[1:]) + """
theorem fermatList_reached : ∀ n ∈ fermatList, Reached n := by
  intro n hn
  simp only [fermatList, List.mem_cons, List.not_mem_nil, or_false] at hn
  rcases hn with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
""" + "".join(f"  · exact {reachname(n)}\n" for n in L) + """
/-- No one-prime extension leaves the list. -/
theorem closed_one : ∀ n0 ∈ fermatList, ∀ q, q.Prime → ¬ q ∣ n0 → FermatType (n0 * q) →
    n0 * q ∈ fermatList := by
  intro n0 hn0 q hq hqn h
  have hq2 := (one_prime_ext (fermatList_fermatType n0 hn0) hq hqn).mp h
  subst hq2
  simp only [fermatList, List.mem_cons, List.not_mem_nil, or_false] at hn0
  rcases hn0 with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
""")
for n0 in L:
    q=n0+2
    if isprime(q): body.append("  · decide\n")
    else: body.append("  · exact absurd hq (by norm_num)\n")
# two-prime helper lemmas
for n0 in L:
    D=n0*n0+n0+1
    sp=subprods(facs[n0])
    lines=[]
    for d in sp:
        if d*d>=D:
            lines.append("  · omega")
            continue
        e=D//d; p=n0+1+d; q=n0+1+e
        if isprime(p) and isprime(q):
            assert n0*p*q in L, (n0,p,q)
            act="decide"
        else:
            cands=[]
            if not isprime(p): cands.append((spf(p),'hp'))
            if not isprime(q): cands.append((spf(q),'hq'))
            w,hname=min(cands)
            act=f"exact absurd {hname} (by norm_num)"
        lines.append(f"  · obtain rfl : e = {e} := by omega\n    {act}")
    body.append(f"""lemma closed_two_{n0} : ∀ d ∈ ({sp} : List ℕ), ∀ e, d * e = {D} → d < e →
    ({n0} + 1 + d).Prime → ({n0} + 1 + e).Prime →
    {n0} * ({n0} + 1 + d) * ({n0} + 1 + e) ∈ fermatList := by
  intro d hd e he hlt hp hq
  simp at hd
  rcases hd with {" | ".join("rfl" for _ in sp)}
""" + "\n".join(lines) + "\n")
body.append("""/-- No two-prime extension leaves the list. -/
theorem closed_two : ∀ n0 ∈ fermatList, ∀ p q, p.Prime → q.Prime → p < q → ¬ p ∣ n0 →
    ¬ q ∣ n0 → FermatType (n0 * p * q) → n0 * p * q ∈ fermatList := by
  intro n0 hn0 p q hp hq hpq hpn hqn h
  have h0 := fermatList_fermatType n0 hn0
  have E := (two_prime_ext h0 hp hq hpq hpn hqn).mp h
  obtain ⟨hp1, hq1⟩ := two_prime_ext_pos h0.pos hp.two_le hpq E
  obtain ⟨d, rfl⟩ : ∃ d, p = n0 + 1 + d := ⟨p - (n0 + 1), by omega⟩
  obtain ⟨e, rfl⟩ : ∃ e, q = n0 + 1 + e := ⟨q - (n0 + 1), by omega⟩
  have hde : d * e = n0 ^ 2 + n0 + 1 := by
    have : (d : ℤ) * e = n0 ^ 2 + n0 + 1 := by
      push_cast at E
      linear_combination E
    exact_mod_cast this
  have hdlt : d < e := by omega
  have hdvd : d ∣ n0 ^ 2 + n0 + 1 := ⟨e, hde.symm⟩
  simp only [fermatList, List.mem_cons, List.not_mem_nil, or_false] at hn0
  rcases hn0 with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
""")
for n0 in L:
    D=n0*n0+n0+1; ps=facs[n0]; sp=subprods(ps)
    alts=[f"exact {certs[p]}" for p in ps if p>=SMALL] + (["norm_num"] if any(p<SMALL for p in ps) else [])
    tac=alts[0] if len(alts)==1 else "first | " + " | ".join(alts)
    pats=" | ".join("rfl" for _ in ps)
    body.append(f"""  · have hd := mem_subprods_of_dvd (d := d) {ps}
      (by intro x hx; simp only [List.mem_cons, List.not_mem_nil, or_false] at hx
          rcases hx with {pats}
          all_goals {tac})
      (by rw [show ({ps} : List ℕ).prod = {n0} ^ 2 + {n0} + 1 by norm_num]; exact hdvd)
    rw [show subprods {ps} = {sp} by decide] at hd
    exact closed_two_{n0} d hd e (by norm_num [hde]) hdlt hp hq
""")
body.append("""/-- Theorem 1.6 (iii): the closure of `1` under one- and two-prime extensions consists of
exactly the eight Fermat-type solutions in `fermatList`. -/
theorem reached_iff (n : ℕ) : Reached n ↔ n ∈ fermatList := by
  constructor
  · intro h
    induction h with
    | one => decide
    | ext1 _ hq hqn hft ih => exact closed_one _ ih _ hq hqn hft
    | ext2 _ hp hq hpq hpn hqn hft ih => exact closed_two _ ih _ _ hp hq hpq hpn hqn hft
  · exact fermatList_reached n

end LehmerTotient
""")
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'LehmerTotient', 'Ext.lean'),'w').write(header+"\n".join(out)+"\n"+"\n".join(body))
print("ok", len(out), "certificates")
