import json, os, sys
# Generates lean/LehmerTotient/EightData.lean from the journal data/companion8/journal.jsonl (Section 7.4): the
# completions s < p < q in integers of the eight-prime search, each with the least divisor d > 1 of p or of q.
here = os.path.dirname(os.path.abspath(__file__))
journal = sys.argv[1] if len(sys.argv) > 1 else os.path.join(here, '..', '..', 'data', 'companion8', 'journal.jsonl')
cs = sorted(tuple(c) for l in open(journal) if l.strip() for c in json.loads(l)['completions'])
assert len(cs) == 21


def least_divisor(x):
    d = 2
    while d * d <= x and d < 10 ** 6:
        if x % d == 0:
            return d
        d += 1
    return None


rows = []
for c in cs:
    pre, (s, p, q) = list(c[:5]), c[5:]
    ds = [d for d in (least_divisor(p), least_divisor(q)) if d]
    rows.append('⟨%s, %d, %d, %d, %d⟩' % (pre, s, p, q, min(ds)))

head = '''import LehmerTotient.Imports

/-!
# The completions of the eight-prime search (Section 7.4)

The search finds 21 completions `s < p < q` in integers, that is, prefixes `p₁, …, p₅` and integers `s < p < q`
with `A' p q + 1 = 2 B' (p - 1)(q - 1)`, where `A' = p₁ ⋯ p₅ s` and `B' = (p₁ - 1) ⋯ (p₅ - 1)(s - 1)`. Each is
listed with a divisor `d` of `p` or of `q`, `1 < d`, smaller than that entry, so that `p` and `q` are not both
prime. The kernel checks all of this (`decide +kernel`). Generated by `scripts/gen_eight.py`.
-/

namespace LehmerTotient

/-- A completion: the prefix, `s = p₆`, the last two entries `p < q`, and a divisor `d` of `p` or `q`. -/
structure Completion where
  pre : List ℕ
  s : ℕ
  p : ℕ
  q : ℕ
  d : ℕ

/-- `A' = p₁ ⋯ p₅ s`. -/
def Completion.A (e : Completion) : ℕ := e.pre.prod * e.s

/-- `B' = (p₁ - 1) ⋯ (p₅ - 1)(s - 1)`. -/
def Completion.B (e : Completion) : ℕ := (e.pre.map (· - 1)).prod * (e.s - 1)

/-- The check: the equation, `s < p < q`, and `d` a proper divisor of `p` or of `q`. -/
def Completion.check (e : Completion) : Bool :=
  (e.A * e.p * e.q + 1 == 2 * e.B * (e.p - 1) * (e.q - 1)) && decide (e.s < e.p) && decide (e.p < e.q) &&
    decide (1 < e.d) && ((decide (e.d < e.p) && e.p % e.d == 0) || (decide (e.d < e.q) && e.q % e.d == 0))

/-- The 21 completions found by the search, in increasing order. -/
def eightCompletions : List Completion := [
  '''

foot = ''']

theorem eightCompletions_length : eightCompletions.length = 21 := by decide +kernel

theorem eightCompletions_check : eightCompletions.all Completion.check = true := by decide +kernel

/-- Each of the 21 completions satisfies `A' p q + 1 = 2 B' (p - 1)(q - 1)` with `s < p < q`, and `p` and `q`
are not both prime. -/
theorem eight_completions {e : Completion} (he : e ∈ eightCompletions) :
    e.A * e.p * e.q + 1 = 2 * e.B * (e.p - 1) * (e.q - 1) ∧ e.s < e.p ∧ e.p < e.q ∧
      ¬ (e.p.Prime ∧ e.q.Prime) := by
  have h := List.all_eq_true.mp eightCompletions_check e he
  simp only [Completion.check, Bool.and_eq_true, Bool.or_eq_true, beq_iff_eq, decide_eq_true_eq] at h
  obtain ⟨⟨⟨⟨heq, hsp⟩, hpq⟩, hd⟩, hdiv⟩ := h
  refine ⟨heq, hsp, hpq, ?_⟩
  rintro ⟨hp, hq⟩
  rcases hdiv with ⟨hdp, hmod⟩ | ⟨hdq, hmod⟩
  · exact Nat.not_prime_of_dvd_of_lt (Nat.dvd_of_mod_eq_zero hmod) hd hdp hp
  · exact Nat.not_prime_of_dvd_of_lt (Nat.dvd_of_mod_eq_zero hmod) hd hdq hq

end LehmerTotient
'''

open(os.path.join(here, '..', 'LehmerTotient', 'EightData.lean'), 'w').write(head + ',\n  '.join(rows) + foot)
print('ok', len(rows), 'completions')
